# -*- coding: utf-8 -*-
from PySide2 import QtCore, QtGui, QtWidgets, __version__
import sqlite3
import terminaltables
import sys

class Ui_AboutDialog(object):

    def setupUi(self, AboutDialog):
        AboutDialog.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)

        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(927, 332)
        font = QtGui.QFont()
        font.setFamily("Arial")
        AboutDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(AboutDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_db_version_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.image_db_version_label.setFont(font)
        self.image_db_version_label.setObjectName("image_db_version_label")
        self.verticalLayout_2.addWidget(self.image_db_version_label)
        self.copyright_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.copyright_label.setFont(font)
        self.copyright_label.setObjectName("copyright_label")
        self.verticalLayout_2.addWidget(self.copyright_label)
        self.backend_version_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.backend_version_label.setFont(font)
        self.backend_version_label.setObjectName("backend_version_label")
        self.verticalLayout_2.addWidget(self.backend_version_label)
        self.python_version_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.python_version_label.setFont(font)
        self.python_version_label.setObjectName("python_version_label")
        self.verticalLayout_2.addWidget(self.python_version_label)
        self.tabWidget.addTab(self.tab, "")
        self.license_tab = QtWidgets.QWidget()
        self.license_tab.setObjectName("license_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.license_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.license_tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_6.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.license_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pyside_v_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pyside_v_label.setFont(font)
        self.pyside_v_label.setObjectName("pyside_v_label")
        self.verticalLayout_3.addWidget(self.pyside_v_label)
        self.qt_v_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.qt_v_label.setFont(font)
        self.qt_v_label.setObjectName("qt_v_label")
        self.verticalLayout_3.addWidget(self.qt_v_label)
        self.sqlite3_v_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.sqlite3_v_label.setFont(font)
        self.sqlite3_v_label.setObjectName("sqlite3_v_label")
        self.verticalLayout_3.addWidget(self.sqlite3_v_label)
        self.terminaltables_v_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.terminaltables_v_label.setFont(font)
        self.terminaltables_v_label.setObjectName("terminaltables_v_label")
        self.verticalLayout_3.addWidget(self.terminaltables_v_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pyside_l_label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pyside_l_label.setFont(font)
        self.pyside_l_label.setObjectName("pyside_l_label")
        self.verticalLayout_5.addWidget(self.pyside_l_label)
        self.qt_l_label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.qt_l_label.setFont(font)
        self.qt_l_label.setObjectName("qt_l_label")
        self.verticalLayout_5.addWidget(self.qt_l_label)
        self.sqlite3_l_label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sqlite3_l_label.setFont(font)
        self.sqlite3_l_label.setObjectName("sqlite3_l_label")
        self.verticalLayout_5.addWidget(self.sqlite3_l_label)
        self.terminaltables_l_label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.terminaltables_l_label.setFont(font)
        self.terminaltables_l_label.setObjectName("terminaltables_l_label")
        self.verticalLayout_5.addWidget(self.terminaltables_l_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pyside_h_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pyside_h_label.setFont(font)
        self.pyside_h_label.setObjectName("pyside_h_label")
        self.verticalLayout_4.addWidget(self.pyside_h_label)
        self.qt_h_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.qt_h_label.setFont(font)
        self.qt_h_label.setObjectName("qt_h_label")
        self.verticalLayout_4.addWidget(self.qt_h_label)
        self.sqlite3_h_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sqlite3_h_label.setFont(font)
        self.sqlite3_h_label.setObjectName("sqlite3_h_label")
        self.verticalLayout_4.addWidget(self.sqlite3_h_label)
        self.terminaltables_h_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.terminaltables_h_label.setFont(font)
        self.terminaltables_h_label.setObjectName("terminaltables_h_label")
        self.verticalLayout_4.addWidget(self.terminaltables_h_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(AboutDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        AboutDialog.setWindowTitle(QtWidgets.QApplication.translate("AboutDialog", "Dialog", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AboutDialog", "Image-db", None, -1))
        self.image_db_version_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Version: 0.5 (Alpha)", None, -1))
        self.copyright_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Copyright © 2019 Taiga Osguthorpe", None, -1))
        self.backend_version_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Backend Version: 2.0", None, -1))
        self.python_version_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Python Version: {0}".format(sys.version), None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("AboutDialog", "General", None, -1))

        self.textBrowser.setHtml(QtWidgets.QApplication.translate("AboutDialog", "Please Read: LICENSE.md", None, -1))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.license_tab), QtWidgets.QApplication.translate("AboutDialog", "License", None, -1))
        self.pyside_v_label.setText(QtWidgets.QApplication.translate("AboutDialog", "PySide2 Version: {0}".format(__version__), None, -1))
        self.qt_v_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Qt Version: {0}".format(QtCore.__version__), None, -1))
        self.sqlite3_v_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Sqlite3 Version: {0} (SQLite: {1})".format(sqlite3.version, sqlite3.sqlite_version), None, -1))
        self.terminaltables_v_label.setText(QtWidgets.QApplication.translate("AboutDialog", "Terminaltables Version: {0}".format(terminaltables.__version__), None, -1))

        self.pyside_l_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)">License</a>', None, -1))
        self.pyside_l_label.setOpenExternalLinks(True)

        self.qt_l_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://www.qt.io/licensing/">Licenses</a>', None, -1))
        self.qt_l_label.setOpenExternalLinks(True)

        self.sqlite3_l_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://github.com/python/cpython/blob/3.7/Lib/sqlite3/__init__.py">License</a>/<a href="https://sqlite.org/copyright.html">SQLite</a>', None, -1))
        self.sqlite3_l_label.setOpenExternalLinks(True)

        self.terminaltables_l_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://github.com/Robpol86/terminaltables/blob/master/LICENSE">License</a>', None, -1))
        self.terminaltables_l_label.setOpenExternalLinks(True)

        self.pyside_h_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://wiki.qt.io/Qt_for_Python">Homepage</a>', None, -1))
        self.pyside_h_label.setOpenExternalLinks(True)

        self.qt_h_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://qt.io">Homepage</a>', None, -1))
        self.qt_h_label.setOpenExternalLinks(True)

        self.sqlite3_h_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://docs.python.org/3/library/sqlite3.html">Homepage</a>/<a href="https://sqlite.org">SQLite</a>', None, -1))
        self.sqlite3_h_label.setOpenExternalLinks(True)

        self.terminaltables_h_label.setText(QtWidgets.QApplication.translate("AboutDialog", '<a href="https://github.com/Robpol86/terminaltables">Homepage</a>', None, -1))
        self.terminaltables_h_label.setOpenExternalLinks(True)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("AboutDialog", "Libraries", None, -1))


if __name__ == "__main__":
    import sys
    sys.exit()
    """import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    ui = Ui_AboutDialog()
    ui.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())"""
